# Generated by Django 5.1.1 on 2024-11-25 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                default=datetime.datetime(2024, 11, 25, 18, 37, 17, 882172)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 25, 18, 37, 17, 882157)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="spotify_access_token",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="spotify_refresh_token",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wraps",
            name="creation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 25, 18, 37, 17, 882757)
            ),
        ),
    ]
