# Generated by Django 5.1.2 on 2024-11-28 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 17, 35, 23, 836833)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 17, 35, 23, 836833)),
        ),
        migrations.AlterField(
            model_name='wraps',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 17, 35, 23, 839909)),
        ),
    ]
