# Generated by Django 5.1.2 on 2024-11-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wraps_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='testing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
