# Generated by Django 5.1.2 on 2024-11-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='testing',
        ),
    ]
