# Generated by Django 5.1.2 on 2024-11-29 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_birthday_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_display_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 22, 28, 8, 151628)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 22, 28, 8, 151617)),
        ),
        migrations.AlterField(
            model_name='wraps',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 22, 28, 8, 152254)),
        ),
    ]
