# Generated by Django 5.1.2 on 2024-11-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spotify_access_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='spotify_refresh_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
