name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint coverage pytest pytest-cov  # Added pytest and pytest-cov for testing

      - name: Run Tests with Coverage
        run: |
          pytest --cov=your_app_directory --cov-fail-under=80  # Use pytest for testing with coverage

      - name: Measure Code Coverage
        run: |
          coverage run -m pytest  # Ensure tests run under coverage
          coverage report
          coverage html

      - name: Check Code Coverage
        run: |
          coverage report --fail-under=80  # Fail if coverage is less than 80%

      - name: Run Pylint
        run: |
          pylint main/  # Ensure correct path to the directory
