name: CI/CD Pipeline

on:
  push:
    branches:
      - Vihaan

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint coverage pytest pytest-cov  # Ensure all necessary tools are included

      - name: Run Tests with Coverage
        run: |
          # Run tests for the 'main' app, excluding main/tests.py from test discovery
          python manage.py test main --ignore=main/tests.py  # Run tests excluding tests.py
      
          # Collect coverage data, excluding main/tests.py from the coverage calculation
          coverage run --source=main --omit="main/tests.py" manage.py test main  # Collect coverage data
          
          # Report coverage and fail if it's below 80%
          coverage report --fail-under=80  # Fail if coverage is below 80%

      - name: Run Pylint
        run: |
          pylint main/ --disable=C0301,C0103,W0311  # Disable line-too-long (C0301) and bad-indentation (C0103) warnings