name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint coverage pytest pytest-cov  # Ensure all necessary tools are included

      - name: Run Tests with Coverage
        run: |
          pytest --cov=main --cov-fail-under=80  # Run tests with coverage directly

      - name: Run Pylint
        run: |
          pylint main/  # Ensure correct path to your application or module