name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Flexibility for any Python 3.x version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure pylint and coverage are in requirements.txt

      - name: Run Pylint
        run: |
          pylint main/  # Adjust to your actual app or module directory

      - name: Run Tests
        run: |
          pytest --max fail=1 --disable-warnings -q  # More efficient for pytest

      - name: Measure Code Coverage
        run: |
          coverage run -m pytest  # Run pytest with coverage
          coverage report  # Show coverage report in console
          coverage html  # Optional: Generate HTML report for local viewing

      - name: Check Code Coverage
        run: |
          coverage report --fail-under=80  # Fail if coverage is below 80%

